import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import logging
from datetime import datetime
from dotenv import load_dotenv

# Import local modules
from store_scraper import StoreScraper
from ai_analyzer import AIAnalyzer

load_dotenv()
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class AppMarketAgent:
    def __init__(self):
        self.store_scraper = StoreScraper()
        self.ai_analyzer = AIAnalyzer()
        
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", 587))
        self.sender_email = os.getenv("SENDER_EMAIL")
        self.sender_password = os.getenv("SENDER_PASSWORD")
        self.recipient_email = "handrake99@gmail.com"

    def generate_report_content(self, store_results: list) -> str:
        report = f"## 📈 일일 유망 앱 마켓 분석 리포트 ({datetime.now().strftime('%Y-%m-%d')})\n\n"
        report += "본 리포트는 니치 마켓, 수익 모델, 1인 개발 가능성을 기준으로 필터링된 잠재력 높은 인디 iOS 앱 목록입니다.\n\n"
        
        report += "### 🏆 엄선된 유망 타겟 앱\n"
        if not store_results:
            report += "조건을 만족하는 앱이 없습니다.\n\n"
        else:
            for i, result in enumerate(store_results, 1):
                app = result['app_metadata']
                eval_reason = result['evaluation_reason']
                report += f"{i}. **{app.get('title')}** (iOS)\n"
                report += f"   - URL: {app.get('url', 'N/A')}\n"
                report += f"   - 출처(검색 키워드): {app.get('source_keyword', 'Unknown')}\n"
                report += f"   - 설명 요약: {app.get('description', '').replace(chr(10), ' ')[:150]}...\n"
                report += f"   - **선정 사유 (LLM 평가):**\n"
                report += f"     - 니치 마켓: {eval_reason.get('niche_market', {}).get('reason', '')}\n"
                report += f"     - 수익 모델: {eval_reason.get('revenue_model', {}).get('reason', '')}\n"
                report += f"     - 기능 단순성: {eval_reason.get('simplicity', {}).get('reason', '')}\n\n"
            
        report += "\n---\n*Generated by App Market Analyzer AI Agent*"
        return report

    def send_email_report(self, markdown_content: str):
        if not all([self.sender_email, self.sender_password]):
            logging.error("Email credentials not fully configured. Storing report to file instead.")
            with open("daily_report.md", "w") as f:
                f.write(markdown_content)
            logging.info("Report saved to daily_report.md")
            return

        msg = MIMEMultipart()
        msg['From'] = self.sender_email
        msg['To'] = self.recipient_email
        msg['Subject'] = f"[App Market Analyzer] 일일 분석 리포트 - {datetime.now().strftime('%Y-%m-%d')}"

        # You'd normally want to convert markdown to HTML here for better email formatting
        # For simplicity, we send it as plain text markdown
        msg.attach(MIMEText(markdown_content, 'plain'))

        try:
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.sender_email, self.sender_password)
            server.send_message(msg)
            server.quit()
            logging.info(f"Successfully sent email report to {self.recipient_email}")
        except Exception as e:
            logging.error(f"Failed to send email: {e}")
            with open("daily_report.md", "w") as f:
                f.write(markdown_content)

    def run(self):
        logging.info("Starting Daily App Market Analysis Cycle...")
        
        # We need a large initial pool since we are filtering them later
        target_store_apps = self.store_scraper.get_top_target_apps(max_pool_size=40)
        
        store_analysis_results = []
        
        # 2. 데이터 수집 및 AI 분석 생략 (LLM Filter Evaluation Only)
        try:
            for app in target_store_apps:
                if len(store_analysis_results) >= 15:
                    break
                    
                # --- V3/V4: LLM Filter Evaluation Only ---
                evaluation = self.ai_analyzer.evaluate_app_potential(app)
                if not evaluation.get("is_approved", False):
                    logging.info(f"App {app.get('title')} rejected by LLM filter: {evaluation}")
                    continue
                
                logging.info(f"App {app.get('title')} approved by LLM filter!")
                
                store_analysis_results.append({
                    'app_metadata': app,
                    'evaluation_reason': evaluation
                })
                 
        except Exception as e:
            if "token/quota limits" in str(e):
                logging.error("🚨 CRITICAL: LLM Token/Quota Limit Exceeded. Halting execution immediately. No email will be sent.")
                return # Abort the execution
            else:
                logging.error(f"Unexpected error during analysis loop: {e}")

        # 4. 리포팅
        report = self.generate_report_content(store_analysis_results)
        self.send_email_report(report)
        logging.info("Daily cycle completed.")

if __name__ == "__main__":
    agent = AppMarketAgent()
    agent.run()
